### ISSUE TITLE
Collection list

### ISSUE THREAD

**Issue by Wanackon** [fidesy/me-sniper#1]
Hi, how can i get collections list in right format to use it in collections.json, by Metaplex i'm assuming?

**Comment by fidesy** [comment]
Hello, actually for parsing I used my own script, but it was implemented 6 months ago and now it doesn't work. 
Actually, I think there is some open API for this purpose.
collections.json is a simple dictionary where key is a mintAddress of NFT and value contains some parameters like collection name, rarity, but its optional, for detecting new collection lists you only need mintAddresses which you can get at https://magiceden.io/mintlist-tool

**Comment by Wanackon** [comment]
Thank you kindly, hash finder exactly what is needed
