### ISSUE TITLE
Transaction too large

### ISSUE THREAD

**Issue by Wanackon** [fidesy/me-sniper#2]
Hi, got an error on few different ME collections:

`2023/01/29 00:21:30 Error while buying nft: (*jsonrpc.RPCError)(0xc00025cdb0)({
 Code: (int) -32602,
 Message: (string) (len=115) "encoded solana_sdk::transaction::versioned::VersionedTransaction too large: 1684 bytes (max: encoded/raw 1644/1232)",
 Data: (interface {}) <nil>
})`

[Collection which generate this issue](https://magiceden.io/marketplace/royale_chess_elements)

Im assuming this error related to ME, cause it's them generated wrong instruction to buy nft, or maybe i can sign transaction in some other way to pass this issue?

**Comment by fidesy** [comment]
Hello, actually it seems strange to use different signature methods. 
Check through the browser the data that ME generates for the transaction and compare if they are identical.
If so, you can read about other signature methods here:
https://github.com/gagliardetto/solana-go
https://github.com/portto/solana-go-sdk
