### ISSUE TITLE
[help wanted] service.Run: telegrambot.New: Not Found

### ISSUE THREAD

**Issue by Web3ViraLabs** [fidesy/me-sniper#4]
Error:-

PS H:\me-sniper> go run cmd/me-sniper/main.go
2024/02/04 01:05:30 service.Run: telegrambot.New: Not Found
exit status 1

My values_yaml.local is:-

solana-endpoint: 'alchemy rpc url'
bot-api-key:
me-api-key:
private-key:

I left bot-api-key, me-api-ey and private-key empty,..
I don't need to bot feature, my goal with this product is to buy nft's of a specified collection using private key

all the packages are installed using "go mod download"

am I doing something wrong here, no clue..,
I'm very new to go Lang, 

waiting for your guide or help
thanks in Advance

**Comment by fidesy** [comment]
Hello, it seems like I lost this feature when refactor code, so I fixed it now, try it again.
